[soldeer]
  remappings_version = false

[dependencies]
  # Core dependencies
  forge-std = "1.9.5"
  "@openzeppelin-contracts" = "5.2.0"
  account-abstraction = { version = "0.8.0", git = "https://github.com/eth-infinitism/account-abstraction", rev="v0.8.0" }